name = "rf-atl-dev"
compatibility_date = "2024-08-10"

# SvelteKit adapter-cloudflare outputs to .svelte-kit/cloudflare/
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env.production]
compatibility_date = "2024-08-10"

# Static assets for SvelteKit
[site]
bucket = ".svelte-kit/cloudflare"
