name = "rf-atl-dev"
compatibility_date = "2024-08-10"
main = ".svelte-kit/output/server/index.js"

[build]
command = "npm run build"

[env.production]
compatibility_date = "2024-08-10"

[site]
bucket = ".svelte-kit/output/client"
